name: Run Tests

on:
  push:
    branches:
    - 'main'
  pull_request:
    branches:
    - 'main'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-go@v5
      with:
        go-version: stable
    - uses: golangci/golangci-lint-action@v8
      with:
        version: v2.1

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: stable
    - name: Run unit tests
      run: go test ./tests -v
    - name: Run unit tests with race detection
      run: go test ./tests -race
    - name: Run benchmarks
      run: go test ./tests -bench=Benchmark -run=^$
